# Default configuration for SLM evaluation (placeholder)

run_name: "dev"
seed: 42

data:
  input_dir: "data/raw"
  output_dir: "data/processed"

benchmark:
  suite: "basic"
  tasks:
    - name: "example_task"
      metric: "accuracy"
      params: {}

model:
  name: "example-slm"
  provider: "local"
  params: {}

logging:
  level: "INFO"
  dir: "logs"

